---
- name: baitap
  hosts: all
  gather_facts: no

  task:
   - name: dat ip cho loopback
     ios_13_interface:
      name: "{{ item.name }}"
      ipv4: "10.0.0.{{ item.ipv4 }}/24"
     with_items:
       - { name: loopback1, ipv4: 1 }
       - { name: loopback2, ipv4: 2 }
       - { name: loopback3, ipv4: 3 }
   - name: show ip
     ios_command:
       commands:
         - show ip int brief
     register: show_ip
     
   - debug: var=show_ip.stdout_lines
