---
- name: baitap123
  hosts: all
  gather_facts: no

  task:
   - name: dat ip cho loopback
     ios_13_interface:
      name: loopback {{ item.number }}
      ipv4: 10.0.{{ item.ipv4 }}.1/24
     with_items:
       - { number: 1 }
       - { number: 2 }
       - { number: 3 }
   - name: show ip
     ios_command:
       commands:
         - show ip int brief
     register: show_ip
     
   - debug: var=show_ip.stdout_lines
