---
- name: baitap
  hosts: all
  gather_facts: no

  task:
   - name: dat ip cho loopback
     ios_13_interface:
      name: "{{ item.name }}"
      ipv4: "{{ item.ipv4 }}"
     with_items:
       - { name: loopback1, ipv4: "10.0.2.1/24" }
       - { name: loopback2, ipv4: "10.0.2.2/24" }
       - { name: loopback3, ipv4: "10.0.2.3/24" }
